# Generated by Django 5.1.3 on 2024-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_member_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='blood',
            field=models.CharField(default='O', max_length=5),
        ),
    ]
