# Generated by Django 5.1.3 on 2024-11-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_member_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='blood',
        ),
    ]
