# Generated by Django 5.1.3 on 2024-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_member_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(blank=True, choices=[('a', 'A+'), ('c', 'c#'), ('d', 'Dart'), ('f', 'Flutter'), ('n', 'Nodejs'), ('n', 'Networking'), ('p', 'Python')], default=None, max_length=20, null=True),
        ),
    ]
