# Generated by Django 5.1.3 on 2024-11-19 15:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A+', 'A+'), ('C#', 'c#'), ('Dart', 'Dart'), ('Fluter', 'Flutter'), ('NodeJs', 'Nodejs'), ('Networking', 'Networking'), ('Python', 'Python')], max_length=42, null=True),
        ),
    ]
