# Generated by Django 5.1.3 on 2024-11-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_group_image_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
    ]
